permalink   : /:categories/:year/:title/
markdown    : kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate, jekyll-gist, jekyll-coffeescript]
paginate: 6
comments: true
paginate_path: "/page/:num"

# source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Artem Plotnikov's blog
author_name: Artem Plotnikov
description: "Artem Plotnikov's blog"
email: a.i.plotn@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://broartem.github.io"
repository: "https://github.com/broartem/broartem.github.io"
disqus_shortname: "aplotnikov"
google_analytics: UA-73121412-1

# social footer
social:
  github:
    slug: github
    link: http://github.com/broartem
  # facebook:
  #   slug: facebook
  #   link: http://facebook.com/fernando.dev
  # twitter:
  #   slug: twitter
  #   link: http://twitter.com/nandomoreirame
  # instagram:
  #   slug: instagram
  #   link: http://instagram.com/nandomoreira.me
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/artemplotnikov
